import json
import os

QUESTS = [
    {"name": "Animal Magnetism", "reqs": {"slayer": 18, "crafting": 19, "ranged": 30, "woodcutting": 35}},
    {"name": "Another Slice of H.A.M.", "reqs": {"attack": 15, "prayer": 25}},
    {"name": "Between a Rock...", "reqs": {"defense": 30, "mining": 40, "smithing": 50}},
    {"name": "Big Chompy Bird Hunting", "reqs": {"cooking": 30, "fletching": 5, "ranged": 30}},
    {"name": "Biohazard", "reqs": {}},
    {"name": "Black Knights' Fortress", "reqs": {"quest points": 12}},
    {"name": "Bone Voyage", "reqs": {"woodcutting": 50, "construction": 50, "magic": 21}},
    {"name": "Cabin Fever", "reqs": {"agility": 42, "crafting": 45, "smithing": 50, "ranged": 40}},
    {"name": "Client of Kourend", "reqs": {}},
    {"name": "Clock Tower", "reqs": {}},
    {"name": "Cold War", "reqs": {"agility": 10, "crafting": 30, "hunter": 10, "construction": 34, "thieving": 15}},
    {"name": "Contact!", "reqs": {}},
    {"name": "Cook's Assistant", "reqs": {}},
    {"name": "Creature of Fenkenstrain", "reqs": {"crafting": 20, "thieving": 25}},
    {"name": "Darkness of Hallowvale", "reqs": {"construction": 5, "mining": 20, "thieving": 22, "agility": 26, "crafting": 32, "magic": 33, "strength": 40}},
    {"name": "Death Plateau", "reqs": {}},
    {"name": "Death to the Dorgeshuun", "reqs": {"agility": 23, "thieving": 23}},
    {"name": "Demon Slayer", "reqs": {}},
    {"name": "Desert Treasure I", "reqs": {"thieving": 53, "firemaking": 50, "slayer": 10, "magic": 50}},
    {"name": "Desert Treasure II", "reqs": {"magic": 75, "firemaking": 75, "thieving": 70, "herblore": 62, "runecraft": 60, "construction": 65}},
    {"name": "Devious Minds", "reqs": {"smithing": 65, "runecraft": 50, "fletching": 50}},
    {"name": "Digsite, The", "reqs": {"agility": 10, "herblore": 10, "thieving": 25}},
    {"name": "Doric's Quest", "reqs": {}},
    {"name": "Dragon Slayer I", "reqs": {"quest points": 32}},
    {"name": "Dragon Slayer II", "reqs": {"magic": 75, "smithing": 70, "mining": 68, "crafting": 62, "agility": 60, "thieving": 60, "construction": 50, "hitpoints": 50}},
    {"name": "Druidic Ritual", "reqs": {}},
    {"name": "Dwarf Cannon", "reqs": {}},
    {"name": "Eadgar's Ruse", "reqs": {"herblore": 31, "agility": 47}},
    {"name": "Eagles' Peak", "reqs": {"hunter": 27}},
    {"name": "Elemental Workshop I", "reqs": {"mining": 20, "smithing": 20, "crafting": 20}},
    {"name": "Elemental Workshop II", "reqs": {"magic": 20, "smithing": 30}},
    {"name": "Enakhra's Lament", "reqs": {"crafting": 50, "firemaking": 45, "prayer": 43, "magic": 39}},
    {"name": "Enlightened Journey", "reqs": {"quest points": 20, "firemaking": 20, "farming": 30, "crafting": 36}},
    {"name": "Ernest the Chicken", "reqs": {}},
    {"name": "Eyes of Glouphrie, The", "reqs": {"magic": 46, "construction": 5}},
    {"name": "Fairy Tale I - Growing Pains", "reqs": {}},
    {"name": "Fairy Tale II - Cure a Queen", "reqs": {"thieving": 40, "farming": 49, "herblore": 57}},
    {"name": "Family Crest", "reqs": {"mining": 40, "smithing": 40, "magic": 59, "crafting": 40}},
    {"name": "Feud, The", "reqs": {"thieving": 30}},
    {"name": "Fight Arena", "reqs": {}},
    {"name": "Fishing Contest", "reqs": {"fishing": 10}},
    {"name": "Forgettable Tale...", "reqs": {"cooking": 22, "farming": 17}},
    {"name": "Fremennik Exiles, The", "reqs": {"crafting": 65, "slayer": 60, "smithing": 60, "fishing": 60, "runecraft": 55}},
    {"name": "Fremennik Isles, The", "reqs": {"construction": 20, "agility": 40}},
    {"name": "Fremennik Trials, The", "reqs": {"fletching": 25, "woodcutting": 40, "crafting": 40}},
    {"name": "Garden of Tranquillity", "reqs": {"farming": 25}},
    {"name": "Gertrude's Cat", "reqs": {}},
    {"name": "Ghosts Ahoy", "reqs": {"cooking": 20, "agility": 25}},
    {"name": "Giant Dwarf, The", "reqs": {"crafting": 12, "firemaking": 16, "magic": 33, "thieving": 14}},
    {"name": "Goblin Diplomacy", "reqs": {}},
    {"name": "Golem, The", "reqs": {"crafting": 20, "thieving": 25}},
    {"name": "Grand Tree, The", "reqs": {"agility": 25}},
    {"name": "Great Brain Robbery, The", "reqs": {"crafting": 16, "construction": 30, "prayer": 50}},
    {"name": "Grim Tales", "reqs": {"farming": 45, "herblore": 52, "thieving": 58, "agility": 59, "woodcutting": 71}},
    {"name": "Hand in the Sand, The", "reqs": {"thieving": 17, "crafting": 49}},
    {"name": "Haunted Mine", "reqs": {"agility": 15, "crafting": 35}},
    {"name": "Hazeel Cult", "reqs": {}},
    {"name": "Heroes' Quest", "reqs": {"quest points": 55, "cooking": 53, "fishing": 53, "herblore": 25, "mining": 50}},
    {"name": "Holy Grail", "reqs": {"attack": 20}},
    {"name": "Horror from the Deep", "reqs": {"agility": 35}},
    {"name": "Icthlarin's Little Helper", "reqs": {}},
    {"name": "Imp Catcher", "reqs": {}},
    {"name": "In Aid of the Myreque", "reqs": {"crafting": 25, "mining": 15, "magic": 7}},
    {"name": "In Search of the Myreque", "reqs": {"agility": 25}},
    {"name": "Jungle Potion", "reqs": {"herblore": 3}},
    {"name": "King's Ransom", "reqs": {"magic": 45, "defence": 65}},
    {"name": "Knight's Sword, The", "reqs": {"mining": 10}},
    {"name": "Legends' Quest", "reqs": {"quest points": 107, "agility": 50, "crafting": 50, "herblore": 45, "magic": 56, "mining": 52, "prayer": 42, "smithing": 50, "strength": 50, "thieving": 50, "woodcutting": 50}},
    {"name": "Lost City", "reqs": {"crafting": 31, "woodcutting": 36}},
    {"name": "Lost Tribe, The", "reqs": {"agility": 13, "thieving": 13, "mining": 17}},
    {"name": "Lunar Diplomacy", "reqs": {"crafting": 61, "defence": 40, "firemaking": 49, "magic": 65, "mining": 60, "woodcutting": 55}},
    {"name": "Making History", "reqs": {"quest points": 71}},
    {"name": "Merlin's Crystal", "reqs": {}},
    {"name": "Misthalin Mystery", "reqs": {}},
    {"name": "Monkey Madness I", "reqs": {}},
    {"name": "Monkey Madness II", "reqs": {"slayer": 69, "crafting": 70, "hunter": 60, "agility": 55, "thieving": 55, "firemaking": 60}},
    {"name": "Monk's Friend", "reqs": {}},
    {"name": "Mountain Daughter", "reqs": {"agility": 20}},
    {"name": "Mourning's End Part I", "reqs": {"ranged": 60, "thieving": 50}},
    {"name": "Mourning's End Part II", "reqs": {"agility": 56}},
    {"name": "Murder Mystery", "reqs": {}},
    {"name": "My Arm's Big Adventure", "reqs": {"woodcutting": 10, "farming": 29}},
    {"name": "Nature Spirit", "reqs": {"crafting": 18}},
    {"name": "Observatory Quest", "reqs": {"crafting": 10}},
    {"name": "Olaf's Quest", "reqs": {"firemaking": 40, "woodcutting": 50}},
    {"name": "One Small Favour", "reqs": {"agility": 36, "crafting": 25, "herblore": 18, "smithing": 30}},
    {"name": "Pirate's Treasure", "reqs": {}},
    {"name": "Plague City", "reqs": {}},
    {"name": "Priest in Peril", "reqs": {}},
    {"name": "Prince Ali Rescue", "reqs": {}},
    {"name": "Rag and Bone Man I", "reqs": {}},
    {"name": "Rag and Bone Man II", "reqs": {"slayer": 40}},
    {"name": "Ratcatchers", "reqs": {}},
    {"name": "Recipe for Disaster", "reqs": {"quest points": 175, "cooking": 70, "agility": 48, "mining": 50, "fishing": 53, "thieving": 53, "herblore": 45, "magic": 59, "smithing": 40, "firemaking": 50, "ranged": 40, "crafting": 40, "fletching": 10, "slayer": 10, "woodcutting": 36}},
    {"name": "Recruitment Drive", "reqs": {"quest points": 12}},
    {"name": "Regicide", "reqs": {"agility": 56, "crafting": 10}},
    {"name": "Restless Ghost, The", "reqs": {}},
    {"name": "Romeo & Juliet", "reqs": {}},
    {"name": "Roving Elves", "reqs": {"agility": 56}},
    {"name": "Royal Trouble", "reqs": {"agility": 40, "slayer": 40}},
    {"name": "Rum Deal", "reqs": {"prayer": 47, "farming": 40, "fishing": 50, "crafting": 42, "slayer": 42}},
    {"name": "Rune Mysteries", "reqs": {}},
    {"name": "Scorpion Catcher", "reqs": {"prayer": 31}},
    {"name": "Sea Slug", "reqs": {"firemaking": 30}},
    {"name": "Shades of Mort'ton", "reqs": {"crafting": 20, "herblore": 15, "firemaking": 5}},
    {"name": "Shadow of the Storm", "reqs": {"crafting": 30}},
    {"name": "Sheep Herder", "reqs": {}},
    {"name": "Sheep Shearer", "reqs": {}},
    {"name": "Shield of Arrav", "reqs": {}},
    {"name": "Shilo Village", "reqs": {"crafting": 20, "agility": 32, "smithing": 4}},
    {"name": "Sins of the Father", "reqs": {"woodcutting": 62, "fletching": 60, "crafting": 56, "magic": 49, "agility": 52, "attack": 50, "slayer": 50}},
    {"name": "Slug Menace", "reqs": {"crafting": 30, "runecraft": 30, "slayer": 30, "thieving": 30}},
    {"name": "Song of the Elves", "reqs": {"agility": 70, "construction": 70, "farming": 70, "herblore": 70, "hunter": 70, "mining": 70, "smithing": 70, "woodcutting": 70}},
    {"name": "Soul's Bane, A", "reqs": {}},
    {"name": "Spirits of the Elid", "reqs": {"magic": 33, "ranged": 37, "mining": 37, "thieving": 37}},
    {"name": "Swan Song", "reqs": {"quest points": 100, "magic": 66, "cooking": 62, "fishing": 62, "smithing": 45, "firemaking": 42, "crafting": 40}},
    {"name": "Tai Bwo Wannai Trio", "reqs": {"agility": 15, "cooking": 30, "fishing": 5}},
    {"name": "Tail of Two Cats, A", "reqs": {}},
    {"name": "Tears of Guthix", "reqs": {"quest points": 43, "firemaking": 49, "crafting": 20, "mining": 20}},
    {"name": "Temple of Ikov", "reqs": {"thieving": 42, "ranged": 40}},
    {"name": "Throne of Miscellania", "reqs": {}},
    {"name": "Tourist Trap, The", "reqs": {"fletching": 10, "smithing": 20}},
    {"name": "Tower of Life", "reqs": {"construction": 10}},
    {"name": "Tree Gnome Village", "reqs": {}},
    {"name": "Tribal Totem", "reqs": {"thieving": 21}},
    {"name": "Troll Romance", "reqs": {"agility": 28}},
    {"name": "Troll Stronghold", "reqs": {"agility": 15}},
    {"name": "Underground Pass", "reqs": {"ranged": 25}},
    {"name": "Vampyre Slayer", "reqs": {}},
    {"name": "Watchtower", "reqs": {"magic": 14, "thieving": 15, "agility": 25, "herblore": 14, "mining": 40}},
    {"name": "Waterfall Quest", "reqs": {}},
    {"name": "What Lies Below", "reqs": {"runecraft": 35}},
    {"name": "Witch's House", "reqs": {}},
    {"name": "Witch's Potion", "reqs": {}},
    {"name": "Zogre Flesh Eaters", "reqs": {"smithing": 4, "herblore": 8, "ranged": 30, "fletching": 30}},
]

with open('c:\\STYFF\\Apps\\osrs-flipper\\backend\\quest_data.py', 'w', encoding='utf-8') as f:
    f.write('QUESTS = ' + json.dumps(QUESTS, indent=4) + '\n')
